# Generated by Django 5.2.17 on 2026-08-12 01:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ars', '0002_seed_defaults'),
    ]

    operations = [
        migrations.AddField(
            model_name='ars',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='arsprogram',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
