# Generated by Django 5.2.17 on 2026-08-05 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Medicine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('generic_name', models.CharField(max_length=200, verbose_name='Generic (medical) term')),
                ('commercial_name', models.CharField(max_length=200)),
                ('concentration', models.CharField(blank=True, max_length=100)),
            ],
            options={
                'ordering': ['generic_name', 'commercial_name'],
                'unique_together': {('generic_name', 'commercial_name', 'concentration')},
            },
        ),
    ]
