# Generated by Django 5.2.17 on 2026-09-03 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicines', '0002_medicine_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicine',
            name='concentracion_unidad',
            field=models.CharField(blank=True, choices=[('mg', 'mg'), ('mcg', 'mcg'), ('g', 'g'), ('ml', 'ml'), ('UI', 'UI'), ('UI/ml', 'UI/ml'), ('%', '%'), ('mg/ml', 'mg/ml'), ('OTRO', 'Otro')], max_length=10),
        ),
        migrations.AddField(
            model_name='medicine',
            name='concentracion_unidad_otro',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='medicine',
            name='concentracion_valor',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='medicine',
            name='forma',
            field=models.CharField(blank=True, choices=[('TABLETA', 'Tableta'), ('CAPSULA', 'Cápsula'), ('JARABE', 'Jarabe'), ('GOTAS', 'Gotas'), ('CREMA', 'Crema'), ('UNGUENTO', 'Ungüento'), ('AMPOLLA', 'Ampolla'), ('VIAL', 'Vial'), ('INHALADOR', 'Inhalador'), ('PARCHE', 'Parche'), ('SUSPENSION', 'Suspensión'), ('SUPOSITORIO', 'Supositorio'), ('OTRO', 'Otro')], max_length=20),
        ),
        migrations.AddField(
            model_name='medicine',
            name='via_pred',
            field=models.CharField(blank=True, choices=[('ORAL', 'Oral'), ('SUBLINGUAL', 'Sublingual'), ('SC', 'SC'), ('IM', 'IM'), ('IV', 'IV'), ('TOPICA', 'Tópica'), ('OFTALMICA', 'Oftálmica'), ('OTICA', 'Ótica'), ('NASAL', 'Nasal'), ('INHALATORIA', 'Inhalatoria'), ('RECTAL', 'Rectal'), ('OTRO', 'Otro')], max_length=20),
        ),
    ]
