# Generated by Django 5.2.17 on 2026-08-29 02:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_user_failed_login_count_user_locked_until'),
        ('centers', '0006_doctorcenterbinding_centers_doc_doctor__b5e1eb_idx'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='center',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managed_by', to='centers.medicalcenter'),
        ),
    ]
