# Generated by Django 5.2.17 on 2026-08-22 23:18

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('login_lockout_threshold', models.PositiveIntegerField(default=5, help_text='Failed logins before an account is locked.', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(50)])),
                ('login_lockout_minutes', models.PositiveIntegerField(default=30, help_text='Lockout duration, in minutes.', validators=[django.core.validators.MinValueValidator(5), django.core.validators.MaxValueValidator(1440)])),
                ('password_min_length', models.PositiveIntegerField(default=8, help_text='Minimum password length enforced at creation/reset.', validators=[django.core.validators.MinValueValidator(8), django.core.validators.MaxValueValidator(64)])),
                ('access_token_lifetime_minutes', models.PositiveIntegerField(default=15, help_text='JWT access token lifetime, in minutes. Capped at 60: access tokens have no revocation on logout (only the refresh token is blacklisted), so this range bounds that exposure window.', validators=[django.core.validators.MinValueValidator(5), django.core.validators.MaxValueValidator(60)])),
                ('refresh_token_lifetime_days', models.PositiveIntegerField(default=3, help_text='JWT refresh token lifetime, in days.', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(30)])),
                ('login_rate_limit_per_min', models.PositiveIntegerField(default=10, help_text='Login attempts allowed per IP per minute.', validators=[django.core.validators.MinValueValidator(3), django.core.validators.MaxValueValidator(120)])),
                ('anon_rate_limit_per_min', models.PositiveIntegerField(default=60, help_text='Anonymous API requests allowed per minute.', validators=[django.core.validators.MinValueValidator(10), django.core.validators.MaxValueValidator(1000)])),
                ('user_rate_limit_per_min', models.PositiveIntegerField(default=300, help_text='Authenticated API requests allowed per minute.', validators=[django.core.validators.MinValueValidator(30), django.core.validators.MaxValueValidator(5000)])),
                ('max_image_upload_mb', models.PositiveIntegerField(default=10, help_text="Maximum record-image upload size, in MB. Keep at or below the nginx client_max_body_size ceiling (100 MB in prod) or larger uploads 413 before Django's validation ever runs.", validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)])),
                ('media_token_ttl_minutes', models.PositiveIntegerField(default=60, help_text='Signed media-URL token lifetime, in minutes. A longer TTL widens the replay window for a leaked signed media URL.', validators=[django.core.validators.MinValueValidator(5), django.core.validators.MaxValueValidator(1440)])),
                ('default_page_size', models.PositiveIntegerField(default=20, help_text='Default page size for list endpoints (still capped at 200).', validators=[django.core.validators.MinValueValidator(5), django.core.validators.MaxValueValidator(100)])),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'System settings',
                'verbose_name_plural': 'System settings',
            },
        ),
    ]
