# Generated by Django 5.2.17 on 2026-08-15 01:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0002_seed_defaults'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicetype',
            name='requires_diagnosis',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='servicetype',
            name='requires_doctor',
            field=models.BooleanField(default=False),
        ),
    ]
