# Generated by Django 5.2.17 on 2026-08-27 13:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0003_servicetype_requires_doctor_diagnosis'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='servicetype',
            name='requires_diagnosis',
        ),
    ]
