# Generated by Django 5.2.17 on 2026-09-02 01:13

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ars', '0003_ars_active_arsprogram_active'),
        ('services', '0004_remove_requires_diagnosis'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServicePrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('active', models.BooleanField(default=True)),
                ('co_pago', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Co-pago')),
                ('ars', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_prices', to='ars.ars')),
                ('ars_program', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='service_prices', to='ars.arsprogram')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prices', to='services.service')),
            ],
            options={
                'ordering': ['service__name', 'ars__name'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('ars_program__isnull', True)), fields=('service', 'ars'), name='uniq_serviceprice_ars_level'), models.UniqueConstraint(condition=models.Q(('ars_program__isnull', False)), fields=('service', 'ars', 'ars_program'), name='uniq_serviceprice_ars_program_level')],
            },
        ),
    ]
