# Generated by Django 5.2.17 on 2026-08-28 15:14

import apps.core.fields
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('appointments', '0004_appointment_cancel_reason_appointment_service'),
        ('patients', '0024_patient_whatsapp_opt_in_patient_whatsapp_opt_in_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CommunicationsSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_name', models.CharField(blank=True, default='', max_length=120)),
                ('reply_to', models.EmailField(blank=True, default='', max_length=254)),
                ('whatsapp_phone_number_id', models.CharField(blank=True, default='', max_length=64)),
                ('whatsapp_business_account_id', models.CharField(blank=True, default='', max_length=64)),
                ('whatsapp_access_token', apps.core.fields.EncryptedCharField(blank=True, default='', max_length=512)),
                ('whatsapp_app_secret', apps.core.fields.EncryptedCharField(blank=True, default='', max_length=512)),
                ('whatsapp_verify_token', models.CharField(blank=True, default='', max_length=255)),
                ('whatsapp_default_country_code', models.CharField(default='+1', max_length=5)),
                ('whatsapp_reminder_hours', models.PositiveIntegerField(default=24)),
                ('whatsapp_master_enabled', models.BooleanField(default=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Communications settings',
                'verbose_name_plural': 'Communications settings',
            },
        ),
        migrations.CreateModel(
            name='OptOut',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('phone_e164', models.CharField(db_index=True, max_length=32)),
                ('reason', models.CharField(blank=True, default='', max_length=255)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='communications_opt_outs', to='patients.patient')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Template',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('channel', models.CharField(choices=[('EMAIL', 'Email'), ('WHATSAPP', 'WhatsApp')], max_length=20)),
                ('kind', models.CharField(choices=[('AVISO', 'Aviso'), ('INFORMACION', 'Informacion'), ('ALERTA', 'Alerta'), ('CITA_CREADA', 'Cita creada'), ('CITA_RECORDATORIO', 'Cita recordatorio'), ('CITA_REAGENDADA', 'Cita reagendada'), ('CITA_CANCELADA', 'Cita cancelada')], max_length=30)),
                ('provider_name', models.CharField(blank=True, default='', max_length=120)),
                ('language', models.CharField(default='es_DO', max_length=10)),
                ('body_email', models.TextField(blank=True, default='')),
                ('variables_json', models.JSONField(blank=True, default=list)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['channel', 'kind'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('channel', 'kind'), name='uniq_active_template_channel_kind')],
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('channel', models.CharField(choices=[('EMAIL', 'Email'), ('WHATSAPP', 'WhatsApp')], max_length=20)),
                ('audience', models.CharField(choices=[('STAFF', 'Staff'), ('PATIENT', 'Patient')], max_length=20)),
                ('kind', models.CharField(choices=[('AVISO', 'Aviso'), ('INFORMACION', 'Informacion'), ('ALERTA', 'Alerta'), ('CITA_CREADA', 'Cita creada'), ('CITA_RECORDATORIO', 'Cita recordatorio'), ('CITA_REAGENDADA', 'Cita reagendada'), ('CITA_CANCELADA', 'Cita cancelada')], max_length=30)),
                ('priority', models.CharField(choices=[('NORMAL', 'Normal'), ('ALERTA', 'Alerta')], default='NORMAL', max_length=10)),
                ('subject', models.CharField(blank=True, default='', max_length=120)),
                ('body', models.TextField(blank=True, default='')),
                ('scheduled_for', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('QUEUED', 'Queued'), ('SENDING', 'Sending'), ('SENT', 'Sent'), ('PARTIAL', 'Partial'), ('FAILED', 'Failed'), ('CANCELLED', 'Cancelled')], default='QUEUED', max_length=10)),
                ('recipient_count', models.PositiveIntegerField(default=0)),
                ('appointment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='communication_messages', to='appointments.appointment')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('template', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='messages', to='communications.template')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Delivery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('address', apps.core.fields.EncryptedCharField(blank=True, default='', max_length=255)),
                ('status', models.CharField(choices=[('QUEUED', 'Queued'), ('SENT', 'Sent'), ('DELIVERED', 'Delivered'), ('READ', 'Read'), ('FAILED', 'Failed'), ('UNDELIVERABLE', 'Undeliverable'), ('OPTED_OUT', 'Opted out'), ('CANCELLED', 'Cancelled')], default='QUEUED', max_length=20)),
                ('attempts', models.PositiveIntegerField(default=0)),
                ('provider_message_id', models.CharField(blank=True, default='', max_length=128)),
                ('error', models.TextField(blank=True, default='')),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('delivered_at', models.DateTimeField(blank=True, null=True)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('appointment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='appointments.appointment')),
                ('patient', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='patients.patient')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deliveries', to='communications.message')),
            ],
            options={
                'indexes': [models.Index(fields=['message'], name='communicati_message_882785_idx'), models.Index(fields=['appointment', 'status'], name='communicati_appoint_b5bfce_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['-created_at'], name='communicati_created_2d065c_idx'),
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['appointment', 'kind'], name='communicati_appoint_b39cdf_idx'),
        ),
    ]
