# Generated by Django 5.2.17 on 2026-09-01 16:20

import apps.core.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('communications', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='communicationssettings',
            name='whatsapp_verify_token',
            field=apps.core.fields.EncryptedCharField(blank=True, default='', max_length=512),
        ),
    ]
