# Generated by Django 5.2.17 on 2026-09-05 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communications', '0003_encrypt_whatsapp_verify_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='delivery',
            name='status',
            field=models.CharField(choices=[('QUEUED', 'Queued'), ('SENDING', 'Sending'), ('SENT', 'Sent'), ('DELIVERED', 'Delivered'), ('READ', 'Read'), ('FAILED', 'Failed'), ('UNDELIVERABLE', 'Undeliverable'), ('OPTED_OUT', 'Opted out'), ('CANCELLED', 'Cancelled')], default='QUEUED', max_length=20),
        ),
    ]
