# Generated by Django 5.2.17 on 2026-08-05 16:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('centers', '0001_initial'),
        ('doctors', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctorcenterbinding',
            name='doctor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='center_bindings', to='doctors.doctorprofile'),
        ),
        migrations.AddField(
            model_name='doctorcenterbinding',
            name='center',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='doctor_bindings', to='centers.medicalcenter'),
        ),
        migrations.AlterUniqueTogether(
            name='doctorcenterbinding',
            unique_together={('doctor', 'center')},
        ),
    ]
