# Generated by Django 5.2.17 on 2026-08-13 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('centers', '0003_doctorcenterbinding_active_medicalcenter_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicalcenter',
            name='is_default',
            field=models.BooleanField(default=False),
        ),
    ]
