# Generated by Django 5.2.17 on 2026-08-13 21:22

from django.db import migrations


def set_incaf_as_default(apps, schema_editor):
    # No-op wherever no code="INCAF" center exists (e.g. test databases,
    # fresh installs before the clinic's center is created).
    MedicalCenter = apps.get_model("centers", "MedicalCenter")
    MedicalCenter.objects.filter(code="INCAF").update(is_default=True)


class Migration(migrations.Migration):

    dependencies = [
        ('centers', '0004_medicalcenter_is_default'),
    ]

    operations = [
        migrations.RunPython(set_incaf_as_default, migrations.RunPython.noop),
    ]
