# Generated by Django 5.2.17 on 2026-08-13 21:22
#
# Demo-branch note: this originally backfilled a specific real clinic's
# center as the installation default. On this branch it instead looks for a
# generic "DEMO"-coded center -- a no-op on a fresh/test database, same as
# the original. `manage.py seed_demo_data` is what actually creates the
# demo center on this branch (see apps/core/management/commands/
# seed_demo_data.py), not a migration -- a migration runs on every install,
# including every test run, and unconditionally creating data there would
# pollute tests that assume a clean MedicalCenter table.

from django.db import migrations


def set_demo_center_as_default(apps, schema_editor):
    MedicalCenter = apps.get_model("centers", "MedicalCenter")
    MedicalCenter.objects.filter(code="DEMO").update(is_default=True)


class Migration(migrations.Migration):

    dependencies = [
        ('centers', '0004_medicalcenter_is_default'),
    ]

    operations = [
        migrations.RunPython(set_demo_center_as_default, migrations.RunPython.noop),
    ]
