# Generated by Django 5.2.17 on 2026-08-20 00:15

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('centers', '0005_set_incaf_as_default'),
        ('doctors', '0006_alter_doctorprofile_code_unique'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='doctorcenterbinding',
            index=models.Index(fields=['doctor', 'approved'], name='centers_doc_doctor__b5e1eb_idx'),
        ),
    ]
