# Generated by Django 5.2.17 on 2026-09-03 19:40

import apps.centers.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('centers', '0006_doctorcenterbinding_centers_doc_doctor__b5e1eb_idx'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicalcenter',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to=apps.centers.models.center_logo_upload_to),
        ),
        migrations.AddField(
            model_name='medicalcenter',
            name='nombre_corto',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='medicalcenter',
            name='nombre_legal',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='medicalcenter',
            name='rnc',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.CreateModel(
            name='MedicalCenterEmail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('center', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='emails', to='centers.medicalcenter')),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='MedicalCenterPhone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=30)),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('center', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='phones', to='centers.medicalcenter')),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
    ]
