# Generated by Django 5.2.17 on 2026-09-03 19:42

import apps.prescriptions.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('appointments', '0004_appointment_cancel_reason_appointment_service'),
        ('centers', '0008_backfill_center_phones_emails'),
        ('doctors', '0009_doctorphonenumber'),
        ('medicines', '0004_backfill_concentracion_valor_unidad'),
        ('patients', '0024_patient_whatsapp_opt_in_patient_whatsapp_opt_in_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Receta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('active', models.BooleanField(default=True)),
                ('fecha', models.DateTimeField()),
                ('proxima_cita_at', models.DateTimeField(blank=True, null=True)),
                ('estado', models.CharField(choices=[('BORRADOR', 'Borrador'), ('EMITIDA', 'Emitida'), ('ANULADA', 'Anulada')], default='BORRADOR', max_length=10)),
                ('pdf', models.FileField(blank=True, null=True, upload_to=apps.prescriptions.models.receta_pdf_upload_to)),
                ('centro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recetas', to='centers.medicalcenter')),
                ('cita', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recetas', to='appointments.appointment')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recetas_created', to=settings.AUTH_USER_MODEL)),
                ('medico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recetas', to='doctors.doctorprofile')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recetas', to='patients.patient')),
            ],
            options={
                'ordering': ['-fecha'],
            },
        ),
        migrations.CreateModel(
            name='RecetaLinea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_impreso', models.CharField(max_length=200)),
                ('cantidad', models.DecimalField(decimal_places=2, max_digits=8)),
                ('concentracion_valor', models.CharField(blank=True, max_length=20)),
                ('unidad', models.CharField(blank=True, max_length=10)),
                ('via', models.CharField(blank=True, max_length=20)),
                ('forma', models.CharField(blank=True, max_length=20)),
                ('fuera_de_catalogo', models.BooleanField(default=False)),
                ('dosis_json', models.JSONField(blank=True, default=dict)),
                ('dosis_texto', models.CharField(blank=True, max_length=300)),
                ('indicacion_extra', models.CharField(blank=True, max_length=300)),
                ('uso_continuo', models.BooleanField(default=False)),
                ('orden', models.PositiveSmallIntegerField(default=0)),
                ('medicamento', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='medicines.medicine')),
                ('receta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lineas', to='prescriptions.receta')),
            ],
            options={
                'ordering': ['orden', 'id'],
            },
        ),
    ]
