# Generated by Django 5.2.17 on 2026-08-05 16:23

import apps.core.fields
import apps.records.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('centers', '0001_initial'),
        ('patients', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ConsultationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('subjective', apps.core.fields.EncryptedTextField(blank=True)),
                ('objective', apps.core.fields.EncryptedTextField(blank=True)),
                ('assessment', apps.core.fields.EncryptedTextField(blank=True)),
                ('plan', apps.core.fields.EncryptedTextField(blank=True)),
                ('notes', apps.core.fields.EncryptedTextField(blank=True)),
                ('center', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='consultation_logs', to='centers.medicalcenter')),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='consultation_logs', to=settings.AUTH_USER_MODEL)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consultation_logs', to='patients.patient')),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='MedicalRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=200)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('diagnosis', apps.core.fields.EncryptedTextField(blank=True)),
                ('treatment', apps.core.fields.EncryptedTextField(blank=True)),
                ('medicine_and_doses', apps.core.fields.EncryptedTextField(blank=True)),
                ('notes', apps.core.fields.EncryptedTextField(blank=True)),
                ('center', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='medical_records', to='centers.medicalcenter')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='authored_records', to=settings.AUTH_USER_MODEL)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medical_records', to='patients.patient')),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='RecordImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('image', models.ImageField(upload_to=apps.records.models.record_image_upload_to)),
                ('caption', models.CharField(blank=True, max_length=255)),
                ('record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='records.medicalrecord')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_record_images', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
