# Generated by Django 5.2.17 on 2026-08-12 01:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0003_medicalrecord_title_trgm_idx'),
    ]

    operations = [
        migrations.AddField(
            model_name='consultationlog',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='medicalrecord',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='recordimage',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
