# Generated by Django 5.2.17 on 2026-08-27 03:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0012_delete_consultationlog'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='medicalrecord',
            options={'ordering': [models.OrderBy(models.F('last_visit_at'), descending=True, nulls_last=True), '-created_at']},
        ),
    ]
