# Generated by Django 5.2.17 on 2026-08-27 15:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0013_alter_medicalrecord_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='aptype',
            options={'ordering': ['category__sort_order', 'category__name', 'sort_order', 'name']},
        ),
    ]
