# Generated by Django 5.2.17 on 2026-09-03 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0015_recordentry_habits'),
    ]

    operations = [
        migrations.AddField(
            model_name='recordimage',
            name='kind',
            field=models.CharField(choices=[('image', 'Image'), ('pdf', 'PDF')], default='image', max_length=10),
        ),
    ]
