# Generated by Django 5.2.17 on 2026-08-15 03:36

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ars', '0003_ars_active_arsprogram_active'),
        ('centers', '0005_set_incaf_as_default'),
        ('doctors', '0006_alter_doctorprofile_code_unique'),
        ('encounters', '0006_encounter_doctor_nullable'),
        ('patients', '0018_backfill_patient_guardian_cedula_search_index'),
        ('rooms', '0006_finalize_room_type_fk'),
        ('services', '0003_servicetype_requires_doctor_diagnosis'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='encounter',
            index=models.Index(fields=['created_at'], name='encounters__created_c35d75_idx'),
        ),
    ]
