# Generated by Django 5.2.17 on 2026-08-31 21:48

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('encounters', '0007_encounter_encounters__created_c35d75_idx'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='encounter',
            name='authorization_number',
        ),
        migrations.AddField(
            model_name='encounterservice',
            name='ars_covered',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='encounterservice',
            name='authorization_number',
            field=models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1)]),
        ),
    ]
