# Generated by Django 5.2.17 on 2026-08-31 22:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('encounters', '0008_remove_encounter_authorization_number_and_more'),
        ('rooms', '0006_finalize_room_type_fk'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='encounter',
            name='doctor',
        ),
        migrations.RemoveField(
            model_name='encounter',
            name='room',
        ),
        migrations.AddField(
            model_name='encounterservice',
            name='room',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='encounter_services', to='rooms.room'),
        ),
    ]
