# Generated by Django 5.2.17 on 2026-09-01 16:15

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ars', '0003_ars_active_arsprogram_active'),
        ('centers', '0006_doctorcenterbinding_centers_doc_doctor__b5e1eb_idx'),
        ('encounters', '0009_remove_encounter_doctor_remove_encounter_room_and_more'),
        ('patients', '0024_patient_whatsapp_opt_in_patient_whatsapp_opt_in_at_and_more'),
        ('services', '0004_remove_requires_diagnosis'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='encounter',
            index=models.Index(fields=['status', 'center', '-completed_at'], name='encounters__status_200014_idx'),
        ),
    ]
