# Generated by Django 5.2.17 on 2026-09-02 00:10

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('encounters', '0010_encounter_encounters__status_200014_idx'),
    ]

    operations = [
        migrations.AlterField(
            model_name='encounterservice',
            name='authorization_number',
            field=models.CharField(blank=True, max_length=20, null=True, validators=[django.core.validators.RegexValidator(message='Authorization number must contain digits only.', regex='^\\d*[1-9]\\d*$')]),
        ),
    ]
