# Generated by Django 5.2.17 on 2026-09-02 01:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('encounters', '0011_alter_encounterservice_authorization_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='encounterservice',
            name='co_pago',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
