# Generated by Django 5.2.17 on 2026-08-05 23:01

import apps.core.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='cedula',
            field=apps.core.fields.EncryptedCharField(blank=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='nss',
            field=apps.core.fields.EncryptedCharField(blank=True),
        ),
    ]
