# Generated by Django 5.2.17 on 2026-08-06 01:15

import apps.core.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ars', '0002_seed_defaults'),
        ('centers', '0002_initial'),
        ('patients', '0002_patient_ars_patient_ars_program_patient_cedula_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='patient',
            options={'ordering': ['search_name']},
        ),
        migrations.RemoveIndex(
            model_name='patient',
            name='patients_pa_last_na_1b32a7_idx',
        ),
        migrations.AddField(
            model_name='patient',
            name='center',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='patients', to='centers.medicalcenter'),
        ),
        migrations.AddField(
            model_name='patient',
            name='search_name',
            field=models.CharField(blank=True, max_length=201),
        ),
        migrations.AlterField(
            model_name='patient',
            name='birth_date',
            field=apps.core.fields.EncryptedCharField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='first_name',
            field=apps.core.fields.EncryptedCharField(),
        ),
        migrations.AlterField(
            model_name='patient',
            name='last_name',
            field=apps.core.fields.EncryptedCharField(),
        ),
    ]
