# Generated by Django 5.2.17 on 2026-08-07 02:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0005_patient_search_name_idx'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='cedula_last4',
            field=models.CharField(blank=True, db_index=True, max_length=4),
        ),
        migrations.AddField(
            model_name='patient',
            name='nss_last4',
            field=models.CharField(blank=True, db_index=True, max_length=4),
        ),
    ]
