# Generated by Django 5.2.17 on 2026-08-12 01:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0008_patient_search_name_trgm_idx'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
