# Generated by Django 5.2.17 on 2026-08-13 15:29

import apps.core.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ars', '0003_ars_active_arsprogram_active'),
        ('centers', '0003_doctorcenterbinding_active_medicalcenter_active'),
        ('patients', '0011_backfill_patient_hash'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='cedula',
            field=apps.core.fields.EncryptedCharField(),
        ),
        migrations.AddConstraint(
            model_name='patient',
            constraint=models.UniqueConstraint(condition=models.Q(('active', True), models.Q(('cedula_hash', ''), _negated=True)), fields=('cedula_hash',), name='uniq_active_patient_cedula_hash'),
        ),
        migrations.AddConstraint(
            model_name='patient',
            constraint=models.UniqueConstraint(condition=models.Q(('active', True), models.Q(('nss_hash', ''), _negated=True)), fields=('nss_hash',), name='uniq_active_patient_nss_hash'),
        ),
    ]
