# Generated by Django 5.2.17 on 2026-08-13 21:17

import apps.core.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0013_alter_patient_birth_date_alter_patient_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='guardian_cedula',
            field=apps.core.fields.EncryptedCharField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='patient',
            name='guardian_first_name',
            field=apps.core.fields.EncryptedCharField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='patient',
            name='guardian_last_name',
            field=apps.core.fields.EncryptedCharField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='patient',
            name='guardian_nss',
            field=apps.core.fields.EncryptedCharField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='patient',
            name='guardian_phone',
            field=apps.core.fields.EncryptedCharField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='patient',
            name='has_guardian',
            field=models.BooleanField(default=True),
        ),
    ]
