# Generated by Django 5.2.17 on 2026-08-13 21:22

from django.db import migrations


def backfill_default_center(apps, schema_editor):
    # Assigns every currently-centerless patient to the default center. A
    # no-op wherever no code="INCAF" center exists (e.g. test databases).
    # Patients already bound to a different center are left untouched.
    # Intentional scoping change: per CLAUDE.md, a nullable `center` means
    # "visible to all staff" -- this removes that open visibility for every
    # patient this backfill touches, scoping them to the default center's
    # approved doctors going forward.
    MedicalCenter = apps.get_model("centers", "MedicalCenter")
    Patient = apps.get_model("patients", "Patient")
    incaf = MedicalCenter.objects.filter(code="INCAF").first()
    if incaf:
        Patient.objects.filter(center__isnull=True).update(center=incaf)


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0014_patient_guardian_fields'),
        ('centers', '0005_set_incaf_as_default'),
    ]

    operations = [
        migrations.RunPython(backfill_default_center, migrations.RunPython.noop),
    ]
