# Generated by Django 5.2.17 on 2026-08-14 18:46

import apps.core.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0015_backfill_default_center'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='allergies',
            field=apps.core.fields.EncryptedTextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='patient',
            name='critical_conditions',
            field=apps.core.fields.EncryptedTextField(blank=True, default=''),
        ),
    ]
