# Generated by Django 5.2.17 on 2026-08-15 00:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0016_patient_allergies_critical_conditions'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='guardian_cedula_hash',
            field=models.CharField(blank=True, db_index=True, max_length=64),
        ),
        migrations.AddField(
            model_name='patient',
            name='guardian_cedula_last4',
            field=models.CharField(blank=True, db_index=True, max_length=4),
        ),
    ]
