# Generated by Django 5.2.17 on 2026-08-22 04:29

import apps.core.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0019_patient_last4_trgm_idx'),
    ]

    operations = [
        migrations.CreateModel(
            name='PatientPhoneNumber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', apps.core.fields.EncryptedCharField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='extra_phones', to='patients.patient')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
    ]
