# Generated by Django 5.2.17 on 2026-08-12 01:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctorprofile',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='doctorschedule',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
