# Generated by Django 5.2.17 on 2026-08-14 18:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0002_doctorprofile_active_doctorschedule_active'),
        ('rooms', '0006_finalize_room_type_fk'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctorprofile',
            name='default_room',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='default_for_doctors', to='rooms.room'),
        ),
    ]
