# Generated by Django 5.2.17 on 2026-08-14 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0003_doctorprofile_default_room'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctorprofile',
            name='code',
            field=models.CharField(blank=True, max_length=12, null=True),
        ),
    ]
