# Generated by Django 5.2.17 on 2026-08-20 01:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0006_alter_doctorprofile_code_unique'),
        ('services', '0003_servicetype_requires_doctor_diagnosis'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctorprofile',
            name='specialty',
        ),
        migrations.AddField(
            model_name='doctorprofile',
            name='services',
            field=models.ManyToManyField(blank=True, related_name='doctors', to='services.service'),
        ),
    ]
