# Generated by Django 5.2.17 on 2026-08-21 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0007_remove_doctorprofile_specialty_and_more'),
        ('rooms', '0006_finalize_room_type_fk'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctorprofile',
            name='rooms',
            field=models.ManyToManyField(blank=True, related_name='assignable_doctors', to='rooms.room'),
        ),
    ]
