# Generated by Django 5.2.17 on 2026-08-22 04:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0008_doctorprofile_rooms'),
    ]

    operations = [
        migrations.CreateModel(
            name='DoctorPhoneNumber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='extra_phones', to='doctors.doctorprofile')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
    ]
