# Generated by Django 5.2.17 on 2026-09-04 15:36, hand-split into
# add-fields / backfill / remove-field (separate migrations) so the
# backfill migration can still read the old `full_name` column.

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0011_backfill_doctorprofile_full_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='doctorprofile',
            options={'ordering': ['last_name', 'first_name', 'code']},
        ),
        migrations.AddField(
            model_name='doctorprofile',
            name='first_name',
            field=models.CharField(blank=True, default='', max_length=150),
        ),
        migrations.AddField(
            model_name='doctorprofile',
            name='last_name',
            field=models.CharField(blank=True, default='', max_length=150),
        ),
    ]
