# Generated by Django 5.2.17 on 2026-08-14 05:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('centers', '0005_set_incaf_as_default'),
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('active', models.BooleanField(default=True)),
                ('code', models.CharField(max_length=20, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('room_type', models.CharField(choices=[('CONSULTATION', 'Consultation'), ('PROCEDURE', 'Procedure'), ('LABORATORY', 'Laboratory'), ('IMAGING', 'Imaging'), ('WAITING', 'Waiting area'), ('OTHER', 'Other')], default='CONSULTATION', max_length=20)),
                ('floor_area', models.CharField(blank=True, max_length=100)),
                ('capacity', models.PositiveIntegerField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('center', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='rooms', to='centers.medicalcenter')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
